FROM node:20-alpine AS development

# Development

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY package.json ./
COPY pnpm-lock.yaml ./

COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json


RUN pnpm install --prefer-offline

COPY apps/notifications apps/notifications
COPY libs libs

RUN pnpm run build notifications

EXPOSE 3004

# Production
FROM node:20-alpine AS production

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install --prod --prefer-offline
COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json

EXPOSE 3004

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/notifications/main"]