FROM node:20-alpine AS development

# Development

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY package.json ./
COPY pnpm-lock.yaml ./

COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json





COPY apps/payments apps/payments
COPY libs libs

RUN pnpm install --prefer-offline -r
# or try pnpm install -r
RUN pnpm run build payments

EXPOSE 3003

# Production
FROM node:20-alpine AS production

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install --prod --prefer-offline
COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json
    
EXPOSE 3003

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/payments/main"]