FROM node:20-alpine AS development

# Development

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install --prefer-offline

COPY . .

RUN pnpm run build

EXPOSE 3003

# Production
FROM node:20-alpine AS production

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install --prod --prefer-offline

EXPOSE 3003

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/payments/main"]